export default {
  character: 'Character',
  characters: 'Characters',
  clear: 'Clear Selection',
  month: 'Month',
  monthAbbreviations: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
  monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' ],
  open: 'Open Calendar',
  presets: {
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    last3Months: 'Last 3 Months',
    last6Months: 'Last 6 Months',
    last9Months: 'Last 9 Months',
    last12Months: 'Last 12 Months',
    nextMonth: 'Next Month',
    next3Months: 'Next 3 Months',
    next6Months: 'Next 6 Months',
    next9Months: 'Next 9 Months',
    next12Months: 'Next 12 Months',
  },
  remaining: 'Remaining',
  required: '(required)',
};